### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by mgcobblestone**

### CODE REVIEW

**Comment by jonathan1055** [comment]
Hi Martin, at first glance this is looking very good. There is only one test failure, which is pretty amazing for the first draft. I have not looked at your code changes in detail yet (will do soon) and I can work on that test failure if you have other things to work at? Overall an excellent start.

**Comment by mgcobblestone** [comment]
Great, thanks, Jonathan!  It would be great if you could look into that error, it's not clear to me why it is happening.  When I look at the page that is being requested in that test, I also do not see the required element/class so I'm not sure if I messed something up or maybe the test needs to be modified?

Currently, the plugins seem to work well for all of the form alter stuff.  Late yesterday, I started looking at the publish method and am still debating whether it makes sense to have a single method that can handle different entity types or if each plugin should implement it's own publish/unpublish methods.  

I started modifying the method in SchedulerManager, but there is a lot going on there.

**Comment by jonathan1055** [comment]
I have created a new branch in my repo called `2096585-entity-plugin` and have merged in the PR commits so far. Then I can test this locally. I think this PR can stay open so you can add more commits to it when ever you want to. Does that make sense with your workflow? I am sure there are many ways of doing this collaboration, and I want to make it as easy for you as possible.

**Comment by jonathan1055** [comment]
Seems the merge automatically closed the PR. Can we re-open it? Let me know how best you'd like to manage this.

**Comment by mgcobblestone** [comment]
I couldn't find an option to re-open that PR so I opened a new one.

**Comment by jonathan1055** [comment]
I have now seen a 'revert' button against my merge notice above. You probably do not see this as I'm the owner. But now that we have #10 I won't do anything with #9 (but useful to know).

**Pull request merged**
